### PR TITLE
Rebuild for OpenMM 7.7

### PR DESCRIPTION
**Pull request by raimis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raimis** [comment]
@conda-forge-admin, please rerender

**Comment by raimis** [comment]
@peastman @jaimergp could you review?

**Comment by jaimergp** [comment]
LGTM!

**Comment by peastman** [comment]
It looks like the only thing you changed is the build number.  Is that because 7.7 broke binary compatibility with the old build?  If so, should we pin the OpenMM version number so it knows which ones go together?

**Comment by jaimergp** [comment]
> should we pin the OpenMM version number so it knows which ones go together?

That's what `pin_compatible` should be doing in the `run` section, iirc!

**Comment by peastman** [comment]
Ok, just making sure!  This looks good then.

**Comment by raimis** [comment]
Yes, `pin_compatible` works and the packages are built for OpenMM 7.7.

**Comment by raimis** [comment]
@jaimergp @peastman could you merge? I don't a permission.

**Comment by jaimergp** [comment]
Done! Feel free to add yourself as a maintainer @raimis!

**Comment by peastman** [comment]
I think you may have to add him.  I just tried, but it looks like I'm not an administrator on this repo.

**Comment by raimis** [comment]
I'll try to add myself as described in https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

**Pull request merged**
