### PR TITLE
Rebuild for openmm 8

### LINKED ISSUE #19: Rebuild for openmm 8?
### Comment:

_No response_

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #19

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
The tests are failing but I am not sure I understand why:

```bash
[  3%] Building CXX object CMakeFiles/OpenMMPlumed.dir/openmmapi/src/PlumedForce.cpp.o
[  7%] Building CXX object CMakeFiles/OpenMMPlumed.dir/openmmapi/src/PlumedForceImpl.cpp.o
[ 11%] Building CXX object CMakeFiles/OpenMMPlumed.dir/serialization/src/PlumedForceProxy.cpp.o
[ 15%] Building CXX object CMakeFiles/OpenMMPlumed.dir/serialization/src/PlumedSerializationProxyRegistration.cpp.o
[ 19%] Linking CXX shared library libOpenMMPlumed.so
[ 19%] Built target OpenMMPlumed
[ 26%] Building CXX object serialization/tests/CMakeFiles/TestSerializePlumedForce.dir/TestSerializePlumedForce.cpp.o
[ 26%] Building CXX object platforms/reference/CMakeFiles/OpenMMPlumedReference.dir/src/ReferencePlumedKernelFactory.cpp.o
[ 30%] Building CXX object platforms/reference/CMakeFiles/OpenMMPlumedReference.dir/src/ReferencePlumedKernels.cpp.o
[ 34%] Linking CXX executable TestSerializePlumedForce
/home/conda/feedstock_root/build_artifacts/openmm-plumed_1676549969527/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/openmm-plumed_1676549969527/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libOpenMM.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[2]: *** [serialization/tests/CMakeFiles/TestSerializePlumedForce.dir/build.make:98: serialization/tests/TestSerializePlumedForce] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: serialization/tests/CMakeFiles/TestSerializePlumedForce.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 38%] Linking CXX shared library libOpenMMPlumedReference.so
[ 38%] Built target OpenMMPlumedReference
make: *** [Makefile:146: all] Error 2
```

**Comment by hadim** [comment]
Seems related to https://github.com/conda-forge/openmm-feedstock/issues/48

Do you have an idea @jaimergp ?

**Comment by hadim** [comment]
I am disabling CUDA 10.2 on Linux. But the osx builds for 3.9 and 3.10 are failing, and I don't have a local osx machine to debug this.

**Comment by peastman** [comment]
I have no idea about the Mac build failures either.  Here's the error:

```
__pycache__._openmmplumed.cpython-310: module references __file__
Couldn't find index page for 'OpenMMPlumed' (maybe misspelled?)
No local packages or working download links found for OpenMMPlumed==1.0
error: Could not find suitable distribution for Requirement.parse('OpenMMPlumed==1.0')
```

Anyone else have an idea?

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
> Any idea why conda-forge does not submit PR to rebuild for any version of openmm?

AFAIK only things in the global pinnings file are "watched". If we have enough packages linking to openmm we can submit it, but so far I think it's only a couple of them? We can discuss it.

> Anyone else have an idea?

About the macOS errors, could this be a case-sensitivity issue? I've been bitten several times by that kind of thing :/

**Comment by raimis** [comment]
I'm fix the pip issue and others in https://github.com/openmm/openmm-plumed/pull/68

**Comment by hadim** [comment]
@raimis I applied the pip fix patch from your PR. Do you mind reviewing and merging so we can get the package without to wait for a new release?

**Review by raimis — APPROVED** [review]

**Comment by raimis** [comment]
@hadim thanks for your effort.

**Pull request merged**
