### PR TITLE
Enable osx_arm64

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #25

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
Same error as in #25, swig does not like the CPU
```/bin/sh: /Users/runner/miniforge3/conda-bld/openmm-plumed_1705661581832/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/swig: Bad CPU type in executable```

**Comment by hadim** [comment]
Maybe try to add `    - swig   # [build_platform != target_platform]` in the `build` section?

**Comment by RaulPPelaez** [comment]
No luck @hadim! Also tried to add this to conda-forge.yaml:
```yaml
test_on_native_only: true
```

**Comment by hadim** [comment]
I tested locally with an M3 and the build works. It means it's indeed related to cross-compilation. But not sure what is causing this...

**Comment by RaulPPelaez** [comment]
I reckon it is related with swig, a build tool, being downloaded for arm64, but we need it compiled for the build machine. Is there a way to download a package for the host architecture?

**Comment by peastman** [comment]
Here's the corresponding section from the openmm-torch recipe, which successfully cross-compiles.

```yaml
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.19                           # [build_platform != target_platform]
    - swig <4.1                              # [build_platform != target_platform]
    - pytorch                                # [build_platform != target_platform]
    - pytorch =*={{ torch_proc_type }}*      # [build_platform != target_platform]
    - openmm >=8.0.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - cmake
    - make
```

The one obvious difference is that it also includes OpenMM.  Try adding

```yaml
    - openmm >=8.1.0                         # [build_platform != target_platform]
```

Note that OpenMM-Plumed now requires 8.1 or later

**Comment by RaulPPelaez** [comment]
I wonder why the same does not work here as in OpenMM-Torch....

**Comment by RaulPPelaez** [comment]
omg, I fixed arm but broke the other one -.-

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
I am not a maintainer but it looks good to me.

**Comment by RaulPPelaez** [comment]
Oh right  -.-
Thanks!

**Pull request merged**
